import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./StoreProvider";
import InfoProvider from "./InfoProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-[2000px] mx-auto `}>
        <div className="min-h-[80vh] ">
          <Providers>
           <InfoProvider>{children}</InfoProvider>
            </Providers>
        </div>
      </body>
    </html>
  );
}
