import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../Component/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-[2000px] mx-auto `}>
        <Navbar></Navbar>
        <div className="min-h-[80vh] ">{children}</div>
        <div className="h-[200px] bg-blue-500">Footer</div>
      </body>
    </html>
  );
}
